### ISSUE TITLE
0.2.54 Doesn't start anymore on Mac

### ISSUE THREAD

**Issue by Fabio-Paccosi** [somiibo/update-server#2]
Hi,

I'm premium user and after update, when app is launching, it infinite loop and restart

<img width="1352" alt="Schermata 2021-02-23 alle 10 28 26" src="https://user-images.githubusercontent.com/59596946/108824334-e0778800-75c1-11eb-8927-5a872f97de56.png">

**Comment by Fabio-Paccosi** [comment]
Edit: same on windows

**Comment by ianwieds** [comment]
@Fabio-Paccosi thanks for the note. This has been resolved!
